### ISSUE TITLE
Lambda additional overhead for overall automation?

### ISSUE THREAD

**Issue by tsheth** [fernandostc/Lambda_Function_Automation_to_Deploy_DSA#1]
Hi,

  Since Cloudwatch event supports SSM document invocation, i think you can use Cloudwatch event for the same invocation. is there a specific reason you are using Lambda to invoke SSM?

you can check my ssm document if you want to use in your code.
https://github.com/tsheth/Deep-Security-unified-ssm

**Comment by fernandostc** [comment]
I don't use lambda to invoke the SSM. I use Lambda to check the InstallDSA tage, Add Tag and add an IAM role to allow the EC2 to run the documents on SSM agent
